### ISSUE TITLE
Decide on documentation format

### ISSUE THREAD

**Issue by Hydroptix** [Hydroptix/csc-307-inventory-app#1]
1. How should internal structures/APIs be documented (Google docs, Github Wiki, etc)?
2. How should user-facing features be documented?
3. Should they be the same?
4. Setup initial index/table of contents page

**Comment by tylerengland25** [comment]
Time Estimate: 1 hour

**Comment by tylerengland25** [comment]
We chose to use GitHub wiki pages for documentation
