### ISSUE TITLE
Create preliminary API endpoint definitions for frontend/backend communication

### ISSUE THREAD

**Issue by Hydroptix** [Hydroptix/csc-307-inventory-app#2]
1. What should the root URL be? (inventory/api/endpoint or inventory/users, etc)
2. What main endpoints should the backend have?
3. How should requests/return data be structured?
4. Document the endpoints somewhere (depends on #1)

**Comment by tylerengland25** [comment]
Time Estimate: 1 hour

**Comment by goodellalex5** [comment]
preliminary API endpoints and JSON structure
API endpoints
/Users
{
    "Username":goodellalex5,
    "UserID":1,
    “InventoryID”:1,
    "links": [
        {"rel":"user","href":"https://inventory.com/Users/1", "action":"GET" },
        {"rel":”user","href":"https://inventory.com/Users/1", "action":"PUT" }
    ]
}
Users/UserID/Inventory
{
    "InventoryID”:1,
    "UserID":1,
    “Items:[
	{“ref”:”song”,”href”:”https://inventory/Songs/1”}
	]
    "links": [
        {"rel":"inventory","href":"https://inventory.com/Users/1/Inventory", "action":"GET" },
        {"rel":"inventory","href":"https://inventory.com/Users/1/Inventory", "action":"PUT" }
    ]
}
/Songs
{
    "itemID":1,
    "Name":”banger”,
     “Artist”: “wow”,
    "Length": “3:30:,
    “Genre”: “rap”,
    “Category” : “playlist1”,
    "links": [
        {"rel":"song","href":"https://inventory.com/Songs/1", "action":"GET" },
        {"rel":"song","href":"https://inventory.com/Songs/1", "action":"PUT" }
    ]
}
Time:1 hr
